# v2.0.0
name: Build Push Messages App New

inputs:
  githubToken:
    description: "GitHub Token"
    required: true
  npmToken:
    description: "NPM Token"
    required: true

runs:
  using: composite

  steps:
    - name: Install dependencies for Client App
      shell: bash
      working-directory: src/VirtoCommerce.PushMessages.Web/push-messages-new
      run: yarn

    - name: Build Client App
      shell: bash
      working-directory: src/VirtoCommerce.PushMessages.Web/push-messages-new
      run: yarn build
